// rpcsx-ui/src/explorer/renderer/ExplorerGridItem.svelte
<script lang="ts">
  import * as itemUtil from "helpers/ExplorerItemUtils";

  export let item: ExplorerItem;
  export let oncontextmenu: (() => void) | undefined;
</script>

<!-- svelte-ignore <a11y_no_static_element_interactions> -->
<div
  class="flex flex-col text-center items-center p-3 gap-3 text-sm rounded bg-neutral-700 hover:bg-neutral-600 active:ring-1 shadow-sm"
  oncontextmenu={() => {
    if (oncontextmenu) oncontextmenu();
  }}
>
  <img
    class="h-[8rem] w-[8rem]"
    src={itemUtil.getIcon(item)}
    alt="{itemUtil.getName(item)} Icon"
    loading="lazy"
  />
  <div class="flex flex-col justify-center items-center w-[8rem] h-[4rem]">
    <h1 class="overflow-hidden line-clamp-2">{itemUtil.getName(item)}</h1>
    <h3 class="overflow-hidden line-clamp-2">{"titleId" in item ? item.titleId : ""}</h3>
  </div>
</div>

// rpcsx-ui/src/explorer/renderer/ExplorerGridItem.tsx
import { ExplorerItem, getIcon, getName } from "./types";

interface ExplorerGridItemProps {
    item: ExplorerItem;
    onContextMenu?: () => void;
}

export default function ExplorerGridItem({ item, onContextMenu }: ExplorerGridItemProps) {
    return (
        <div 
            className="flex flex-col text-center items-center p-3 gap-3 text-sm rounded bg-neutral-700 hover:bg-neutral-600 active:ring-1 shadow-sm"
            onContextMenu={(e) => {
                if (onContextMenu) {
                    e.preventDefault();
                    onContextMenu();
                }
            }}
        >
            <img
                className="h-[8rem] w-[8rem]"
                src={getIcon(item) || '/default-icon.png'}
                alt={`${getName(item)} Icon`}
                loading="lazy"
            />
            <div className="flex flex-col justify-center items-center w-[8rem] h-[4rem]">
                <h1 className="overflow-hidden line-clamp-2">{getName(item)}</h1>
                <h3 className="overflow-hidden line-clamp-2">{item.titleId ? item.titleId : ""}</h3>
            </div>
        </div>
    );
}
